[project]
name = "sharkadm"
version = "0.1.3"
description = "Handles workflows for Swedish NODC"
authors = [
    {name = "Magnus Wenzer", email = "magnus.wenzer@smhi.se"},
]
dependencies = [
    "pyyaml==6.0.1",
    "pyproj>=3.6.1",
    "openpyxl==3.1.2",
    "pandas>=2.2.1",
    "requests>=2.31.0",
    "xlsxwriter>=3.2.0",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = [
    "-e file:///C:/mw/git/nodc-bvol#egg=nodc-bvol",
    "-e file:///C:/mw/git/nodc-codes#egg=nodc-codes",
    "-e file:///C:/mw/git/nodc-dyntaxa#egg=nodc-dyntaxa",
    "-e file:///C:/mw/git/nodc-geography#egg=nodc-geography",
    "-e file:///C:/mw/git/nodc-station#egg=nodc-station",
    "-e file:///C:/mw/git/nodc-worms#egg=nodc-worms",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
mypkg = ["."]
