data_type: phytoplankton
levels:
  sample:
    - visit_year
    - platform_code
    - visit_id
    - visit_date
    - sample_time
    - reported_station_name
    - sample_min_depth_m
    - sample_max_depth_m
