from sharkadm.validators.station.coordinates_dm import ValidateCoordinatesDm
from sharkadm.validators.station.coordinates_sweref99 import ValidateCoordinatesSweref99
from sharkadm.validators.station.name_in_master import ValidateNameInMaster
from sharkadm.validators.station.position_in_ocean import ValidatePositionInOcean
from sharkadm.validators.station.position_within_station_radius import (
    ValidatePositionWithinStationRadius,
)
from sharkadm.validators.station.synonym_in_master import ValidateSynonymsInMaster
