PROFILE:
  ADD_SMP: additional_sampling
  AIRPRES: air_pressure_hpa
  AIRTEMP: air_temperature_degc
  ALABO: analytical_laboratory_code
  CLOUD: cloud_observation_code
  COMNT_VISIT: visit_comment
  CRUISE_NO: expedition_id
  EDATE: sample_enddate
  ETIME: sample_endtime
  FILE_NAME: profile_file_name
  FILE_NAME_DATABASE: profile_file_name_db
  ICEOB: ice_observation_code
  INSTRUMENT_ID: instrument_id
  LATIT: visit_reported_latitude
  LONGI: visit_reported_longitude
  MPROG: monitoring_program_code
  MYEAR: visit_year
  ORDERER: sample_orderer_code
  POSYS: positioning_system_code
  PROJ: sample_project_name
  REFSK_ANA: analysis_method_reference_code
  REV_DATE: revision_date
  SDATE: visit_date
  SERNO: visit_id
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMTYP: sampler_type_code
  STATN: reported_station_name
  STIME: sample_time
  WADEP: water_depth_m
  WAVES: wave_observation_code
  WEATH: weather_observation_code
  WINDIR: wind_direction_code
  WINSP: wind_speed_ms
profile:
  ADD_SMP: additional_sampling
  AIRPRES: air_pressure_hpa
  AIRTEMP: air_temperature_degc
  ALABO: analytical_laboratory_code
  CLOUD: cloud_observation_code
  COMNT_VISIT: visit_comment
  CRUISE_NO: expedition_id
  EDATE: sample_enddate
  ETIME: sample_endtime
  FILE_NAME: profile_file_name
  FILE_NAME_DATABASE: profile_file_name_db
  ICEOB: ice_observation_code
  INSTRUMENT_ID: instrument_id
  LATIT: visit_reported_latitude
  LONGI: visit_reported_longitude
  MPROG: monitoring_program_code
  MYEAR: visit_year
  ORDERER: sample_orderer_code
  POSYS: positioning_system_code
  PROJ: sample_project_name
  REFSK_ANA: analysis_method_reference_code
  REV_DATE: revision_date
  SDATE: visit_date
  SERNO: visit_id
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMTYP: sampler_type_code
  STATN: reported_station_name
  STIME: sample_time
  WADEP: water_depth_m
  WAVES: wave_observation_code
  WEATH: weather_observation_code
  WINDIR: wind_direction_code
  WINSP: wind_speed_ms
