Bact_BIOMAD:
  ACKR_SMP: sampling_laboratory_accreditated
  ALABO: analytical_laboratory_code
  BCTCNT: COPY_VARIABLE.Bacterial concentration.cells/l
  BCTPR: COPY_VARIABLE.Bacterial production.cells/l/d
  CNTFLG: QFLAG.Bacterial concentration
  COMNT: sample_comment
  LATIT: visit_reported_latitude
  LONGI: visit_reported_longitude
  METFP: preservation_method_code
  MYEAR: visit_year
  ORDERER: sample_orderer_code
  PRFLG: QFLAG.Bacterial production
  PROJ: sample_project_code
  "R\xE4ttningskommentar": variable_comment
  SDATE: visit_date
  SERNO: sample_series
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMDEP: sample_depth_m
  SMPNO: sample_id
  SMTYP: sampler_type_code
  STATN: reported_station_name
  STIME: sample_time
  WADEP: water_depth_m
  WLTYP: water_land_station_type_code
Bact_FCM:
  ABUND: COPY_VARIABLE.Abundance.ind/l or 100 um pieces/l
  ACKR_SMP: sampling_laboratory_accreditated
  ALABO: analytical_laboratory_code
  ANADATE: analysis_date
  BIOVOL: COPY_VARIABLE.Biovolume concentration.mm3/l
  CEVOL: reported_cell_volume_um3
  CEVOL_UM3: reported_cell_volume_um3
  CLOUD: cloud_observation_code
  COMNT_SAMP: sample_comment
  COMNT_SMP: sample_comment
  COMNT_VISIT: visit_comment
  COUNT: COPY_VARIABLE.# counted.ind/analysed sample fraction
  CRUISE_NO: expedition_id
  C_CONC: COPY_VARIABLE.Carbon concentration.ugC/l
  EXPID: expedition_id
  ICEOB: ice_observation_code
  LATIT: visit_reported_latitude
  LATNM: reported_scientific_name
  LONGI: visit_reported_longitude
  METDC: method_documentation
  METFP: preservation_method_code
  METOA: analysis_method_code
  MNDEP: sample_min_depth_m
  MPROG: monitoring_program_code
  MSTAT: monitoring_station_type_code
  MXDEP: sample_max_depth_m
  MYEAR: visit_year
  ORDERER: sample_orderer_code
  PDMET: plankton_sampling_method_code
  POSYS: positioning_system_code
  PROJ: sample_project_code
  PURPM: monitoring_purpose_code
  REFSK: method_reference_code
  REPLI_NO: replicate_no
  SDATE: visit_date
  SECCHI: secchi_depth_m
  SERNO: sample_series
  SFLAG: species_flag_code
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMPDEP: sample_depth_m
  SMPNO: sample_id
  SMTYP: sampler_type_code
  SMVOL: sampled_volume_l
  STATN: reported_station_name
  STIME: sample_time
  TRPHY: trophic_type_code
  WADEP: water_depth_m
  WAVES: wave_observation_code
  WEATH: weather_observation_code
  WINDIR: wind_direction_code
  WINSP: wind_speed_ms
  mgC/m3: COPY_VARIABLE.Carbon concentration.ugC/l
Bact_abu:
  ACKR_ANA: analytical_laboratory_accreditated
  ACKR_SMP: sampling_laboratory_accreditated
  ALABO: analytical_laboratory_code
  ANADATE: analysis_date
  ANA_RESP: analysed_by
  BABUFLG: QFLAG.Bacterial concentration
  BACDENS: COPY_VARIABLE.Bacterial cell carbon content.fg C/cell
  BACOEFF: coefficient
  BACTABU: COPY_VARIABLE_MULTIPLY.Bacterial concentration.cells/l.1000
  BACTDENS: COPY_VARIABLE.Bacterial cell carbon content.fg C/cell
  BACVOL: COPY_VARIABLE.Bacterial cell volume.um3/cell
  BAVOLFLG: QFLAG.Bacterial cell volume
  BCTABU: COPY_VARIABLE_MULTIPLY.Bacterial concentration.cells/l.1000
  BCTCNT: COPY_VARIABLE.Bacterial concentration.cells/l
  BCTVOL: COPY_VARIABLE.Bacterial cell volume.um3/cell
  BGFLG: QFLAG.Bacterial production
  CLOUD: cloud_observation_code
  COEFF: coefficient
  COMNT_SAMP: sample_comment
  COMNT_VAR: variable_comment
  COMNT_VISIT: visit_comment
  CPORT: counted_portions
  CRUISE_NO: expedition_id
  ICEOB: ice_observation_code
  LATIT: visit_reported_latitude
  LONGI: visit_reported_longitude
  METDC: method_documentation
  METFP: preservation_method_code
  METOA: analysis_method_code
  MPROG: monitoring_program_code
  MSTAT: monitoring_station_type_code
  MYEAR: visit_year
  ORDERER: sample_orderer_code
  POSYS: positioning_system_code
  PROJ: sample_project_code
  REFSK: method_reference_code
  SDATE: visit_date
  SECCHI: secchi_depth_m
  SERNO: sample_series
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMPDEP: sample_depth_m
  SMPLAT: sample_reported_latitude
  SMPLONG: sample_reported_longitude
  SMPNO: sample_id
  SMTYP: sampler_type_code
  SMVOL: sampled_volume_l
  SPVOL: analysed_volume_cm3
  STATN: reported_station_name
  STIME: sample_time
  SUBNO: sample_part_id
  WADEP: water_depth_m
  WAVES: wave_observation_code
  WEATH: weather_observation_code
  WINDIR: wind_direction_code
  WINSP: wind_speed_ms
Bact_abu_2:
  ACKR_ANA: analytical_laboratory_accreditated
  ACKR_SMP: sampling_laboratory_accreditated
  ALABO: analytical_laboratory_code
  ANADATE: analysis_date
  ANA_RESP: analysed_by
  BABUFLG: QFLAG.Bacterial concentration
  BACDENS: COPY_VARIABLE.Bacterial cell carbon content.fg C/cell
  BACOEFF: coefficient
  BACTABU: COPY_VARIABLE.Bacterial concentration.cells/ml
  BACTDENS: COPY_VARIABLE.Bacterial cell carbon content.fg C/cell
  BACVOL: COPY_VARIABLE.Bacterial cell volume.um3/cell
  BAVOLFLG: QFLAG.Bacterial cell volume
  BCTABU: COPY_VARIABLE.Bacterial concentration.cells/ml
  BCTVOL: COPY_VARIABLE.Bacterial cell volume.um3/cell
  BGFLG: QFLAG.Bacterial production
  CLOUD: cloud_observation_code
  COEFF: coefficient
  COMNT_SAMP: sample_comment
  COMNT_VAR: variable_comment
  COMNT_VISIT: visit_comment
  CPORT: counted_portions
  CRUISE_NO: expedition_id
  ICEOB: ice_observation_code
  LATIT: visit_reported_latitude
  LONGI: visit_reported_longitude
  METDC: method_documentation
  METFP: preservation_method_code
  METOA: analysis_method_code
  MPROG: monitoring_program_code
  MSTAT: monitoring_station_type_code
  MYEAR: visit_year
  ORDERER: sample_orderer_code
  POSYS: positioning_system_code
  PROJ: sample_project_code
  REFSK: method_reference_code
  SDATE: visit_date
  SECCHI: secchi_depth_m
  SERNO: sample_series
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMPDEP: sample_depth_m
  SMPLAT: sample_reported_latitude
  SMPLONG: sample_reported_longitude
  SMPNO: sample_id
  SMTYP: sampler_type_code
  SMVOL: sampled_volume_l
  SPVOL: analysed_volume_cm3
  STATN: reported_station_name
  STIME: sample_time
  SUBNO: sample_part_id
  WADEP: water_depth_m
  WAVES: wave_observation_code
  WEATH: weather_observation_code
  WINDIR: wind_direction_code
  WINSP: wind_speed_ms
Bact_gr:
  ACKR_ANA: analytical_laboratory_accreditated
  ACKR_SMP: sampling_laboratory_accreditated
  ALABO: analytical_laboratory_code
  ANADATE: analysis_date
  ANA_RESP: analysed_by
  BACVOL: COPY_VARIABLE.Bacterial cell volume.um3/cell
  BAVOLFLG: QFLAG.Bacterial cell volume
  BCTGR: COPY_VARIABLE.Bacterial production.cells/l/d
  BCTPR: COPY_VARIABLE.Bacterial production.cells/l/d
  BCTVOL: COPY_VARIABLE.Bacterial cell volume.um3/cell
  BGCELLP: COPY_VARIABLE.Bacterial production.cells/l/d
  BGFLG: QFLAG.Bacterial production
  BGRFLG: QFLAG.Bacterial production
  BGTCF: coefficient
  CLOUD: cloud_observation_code
  COMNT_SAMP: sample_comment
  COMNT_VAR: variable_comment
  COMNT_VISIT: visit_comment
  CRUISE_NO: expedition_id
  ICEOB: ice_observation_code
  LATIT: visit_reported_latitude
  LONGI: visit_reported_longitude
  METDC: method_documentation
  METFP: preservation_method_code
  MPROG: monitoring_program_code
  MSTAT: monitoring_station_type_code
  MYEAR: visit_year
  ORDERER: sample_orderer_code
  POSYS: positioning_system_code
  PRFLG: QFLAG.Bacterial production
  PROJ: sample_project_code
  REFSK: method_reference_code
  SDATE: visit_date
  SECCHI: secchi_depth_m
  SERNO: sample_series
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMPDEP: sample_depth_m
  SMPLAT: sample_reported_latitude
  SMPLONG: sample_reported_longitude
  SMPNO: sample_id
  SMTYP: sampler_type_code
  SMVOL: sampled_volume_l
  SPVOL: analysed_volume_cm3
  STATN: reported_station_name
  STIME: sample_time
  SUBNO: sample_part_id
  WADEP: water_depth_m
  WAVES: wave_observation_code
  WEATH: weather_observation_code
  WINDIR: wind_direction_code
  WINSP: wind_speed_ms
