ZP_JELLY:
  ABUND: COPY_VARIABLE.Abundance.ind/m3
  ACKR_ANA: analytical_laboratory_accreditated
  ACKR_SMP: sampling_laboratory_accreditated
  AIRPRES: air_pressure_hpa
  AIRTEMP: air_temperature_degc
  ALABO: analytical_laboratory_code
  ANADATE: analysis_date
  ANA_RESP: analysed_by
  BMCCONT: COPY_VARIABLE.Carbon content.ug/m3
  BODY_LGTH: COPY_VARIABLE.Body length.mm
  CLMET: calculation_method
  CLOUD: cloud_observation_code
  COMNT_ABUN: variable_comment
  COMNT_SAMP: sample_comment
  COMNT_SAMPLE: sample_comment
  COMNT_VAR: variable_comment
  COMNT_VISIT: visit_comment
  COUNT: COPY_VARIABLE.# counted.ind/analysed sample fraction
  COUNTNR: COPY_VARIABLE.# counted.ind/analysed sample fraction
  CPORT: counted_portions
  CRUISE_NO: expedition_id
  DRYWT: COPY_VARIABLE.Dry weight.mg/analysed sample fraction
  EXPID: expedition_id
  FLOW_READ: flowmeter_length_m
  ICEOB: ice_observation_code
  INDCOUNT: COPY_VARIABLE.# counted.ind/analysed sample fraction
  INDWETWT: used_indwetwt.MULTIPLY.1000
  INDWETWT_ug: used_indwetwt.DIVIDE.1000
  LATIT: visit_reported_latitude
  LATNM: reported_scientific_name
  LENGTH: length_mm
  LONGI: visit_reported_longitude
  MAGNI: magnification
  MESHS: mesh_size_um
  METDC: method_documentation
  METFP: preservation_method_code
  MNDEP: sample_min_depth_m
  MPROG: monitoring_program_code
  MSTAT: monitoring_station_type_code
  MXDEP: sample_max_depth_m
  MYEAR: visit_year
  NPORT: number_of_portions
  ORDERER: sample_orderer_code
  PDMET: plankton_sampling_method_code
  POSYS: positioning_system_code
  PROJ: sample_project_code
  PROJ_NAME: sample_project_code
  QFLAG: quality_flag
  Q_SECCHI: secchi_depth_quality_flag
  REFSK: method_reference_code
  SAREA: sampler_area_cm2
  SDATE: visit_date
  SEAST: wave_observation_code
  SECCHI: secchi_depth_m
  SERNO: visit_id
  SEXCO: sex_code
  SEXCODE: sex_code
  SFLAG: species_flag_code
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMPID: sample_id
  SMPNO: sample_id
  SMTYP: sampler_type_code
  SMVOL: sampled_volume_l
  SPLIT: sample_splitting_code
  STAGE: dev_stage_code
  STATN: reported_station_name
  STIME: sample_time
  TAXNM: taxonomist
  VFLAG: quality_flag
  WADEP: water_depth_m
  WAVES: wave_observation_code
  WEATH: weather_observation_code
  WETWT: used_indwetwt.MULTIPLY.1000
  WETWTM3: COPY_VARIABLE_MULTIPLY.Wet weight/volume.mg/m3.1000
  WINDIR_CODE: wind_direction_code
  WINDR: wind_direction_code
  WINSP: wind_speed_ms
  WIRAN: wire_angle_deg
  WLTYP: water_land_station_type_code
ZP_REG:
  ACKR_ANA: analytical_laboratory_accreditated
  ACKR_SMP: sampling_laboratory_accreditated
  AIRPRES: air_pressure_hpa
  AIRTEMP: air_temperature_degc
  ALABO: analytical_laboratory_code
  ANADATE: analysis_date
  ANA_RESP: analysed_by
  BMCCONT: COPY_VARIABLE.Carbon content.ug/m3
  CCONT: COPY_VARIABLE.Carbon content.ug/analysed sample fraction
  CLMET: calculation_method
  CLOUD: cloud_observation_code
  COMNT_ABUN: variable_comment
  COMNT_SAMP: sample_comment
  COMNT_SAMPLE: sample_comment
  COMNT_SITE: visit_comment
  COMNT_VAR: variable_comment
  COMNT_VISIT: visit_comment
  COMT_VISIT: visit_comment
  COUNT: COPY_VARIABLE.# counted.ind/analysed sample fraction
  COUNTNR: COPY_VARIABLE.# counted.ind/analysed sample fraction
  CPORT: counted_portions
  CRUIS: expedition_id
  CRUISE_NO: expedition_id
  DRYWT: COPY_VARIABLE.Dry weight.mg/analysed sample fraction
  EXPID: expedition_id
  FLOW_READ: flowmeter_length_m
  ICEOB: ice_observation_code
  INDCOUNT: COPY_VARIABLE.# counted.ind/analysed sample fraction
  INDWETWT: used_indwetwt.MULTIPLY.1000
  INDWETWT_ug: used_indwetwt.DIVIDE.1000
  LATIT: visit_reported_latitude
  LATNM: reported_scientific_name
  LENGTH_MEAN: COPY_VARIABLE.Length (mean).um
  LENGTH_MEDIAN: COPY_VARIABLE.Length (median).um
  LONGI: visit_reported_longitude
  MAGNI: magnification
  MESHS: mesh_size_um
  METDC: method_documentation
  METFP: preservation_method_code
  MNDEP: sample_min_depth_m
  MPROG: monitoring_program_code
  MSTAT: monitoring_station_type_code
  MXDEP: sample_max_depth_m
  MYEAR: visit_year
  NPORT: number_of_portions
  ORDERER: sample_orderer_code
  PDMET: plankton_sampling_method_code
  POSYS: positioning_system_code
  PROJ: sample_project_code
  PROJ_NAME: sample_project_code
  PURPM: monitoring_purpose_code
  QFLAG: quality_flag
  Q_SECCHI: secchi_depth_quality_flag
  REFSK: method_reference_code
  SAREA: sampler_area_cm2
  SDATE: visit_date
  SEAST: wave_observation_code
  SECCHI: secchi_depth_m
  SERNO: visit_id
  SEXCO: sex_code
  SEXCODE: sex_code
  SFLAG: species_flag_code
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMPID: sample_id
  SMPNO: sample_id
  SMTYP: sampler_type_code
  SMVOL: sampled_volume_l
  SPLIT: sample_splitting_code
  STAGE: dev_stage_code
  STATN: reported_station_name
  STIME: sample_time
  TAXNM: taxonomist
  VFLAG: quality_flag
  WADEP: water_depth_m
  WAVES: wave_observation_code
  WEATH: weather_observation_code
  WETWT: COPY_VARIABLE.Wet weight.mg/analysed sample fraction
  WINDIR: wind_direction_code
  WINDIR_CODE: wind_direction_code
  WINDR: wind_direction_code
  WINSP: wind_speed_ms
  WIRAN: wire_angle_deg
  WLTYP: water_land_station_type_code
ZP_SUSE:
  ABUND/M2: COPY_VARIABLE.Abundance.ind/m2
  ABUNDM2: COPY_VARIABLE.Abundance.ind/m2
  ABUNDM3: COPY_VARIABLE.Abundance.ind/m3
  ACKR_ANA: analytical_laboratory_accreditated
  ACKR_SMP: sampling_laboratory_accreditated
  AIRPRES: air_pressure_hpa
  AIRTEMP: air_temperature_degc
  ALABO: analytical_laboratory_code
  ANADATE: analysis_date
  ANA_RESP: analysed_by
  CCONT: COPY_VARIABLE.Carbon content.ug/analysed sample fraction
  CLMET: calculation_method
  CLOUD: cloud_observation_code
  COMNT_ABUN: variable_comment
  COMNT_SAMP: sample_comment
  COMNT_SAMPLE: sample_comment
  COMNT_SITE: visit_comment
  COMNT_VAR: variable_comment
  COMNT_VISIT: visit_comment
  COMT_VISIT: visit_comment
  COUNT: COPY_VARIABLE.# counted.ind/analysed sample fraction
  COUNTNR: COPY_VARIABLE.# counted.ind/analysed sample fraction
  CPORT: counted_portions
  CRUIS: expedition_id
  CRUISE_NO: expedition_id
  DRYWT: COPY_VARIABLE.Dry weight.mg/analysed sample fraction
  EXPID: expedition_id
  FLOW_READ: flowmeter_length_m
  ICEOB: ice_observation_code
  INDCOUNT: COPY_VARIABLE.# counted.ind/analysed sample fraction
  INDWETWT: used_indwetwt.MULTIPLY.1000
  INDWETWT_g: used_indwetwt.MULTIPLY.1000
  INDWETWT_ug: used_indwetwt.DIVIDE.1000
  LATIT: visit_reported_latitude
  LATNM: reported_scientific_name
  LONGI: visit_reported_longitude
  MAGNI: magnification
  MESHS: mesh_size_um
  METDC: method_documentation
  METFP: preservation_method_code
  MNDEP: sample_min_depth_m
  MPROG: monitoring_program_code
  MSTAT: monitoring_station_type_code
  MXDEP: sample_max_depth_m
  MYEAR: visit_year
  NPORT: number_of_portions
  ORDERER: sample_orderer_code
  PDMET: plankton_sampling_method_code
  POSYS: positioning_system_code
  PROJ: sample_project_code
  PROJ_NAME: sample_project_code
  PURPM: monitoring_purpose_code
  QFLAG: quality_flag
  Q_SECCHI: secchi_depth_quality_flag
  REFSK: method_reference_code
  SAREA: sampler_area_cm2
  SDATE: visit_date
  SEAST: wave_observation_code
  SECCHI: secchi_depth_m
  SERNO: visit_id
  SEXCO: sex_code
  SEXCODE: sex_code
  SFLAG: species_flag_code
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMPID: sample_part_id
  SMPNO: sample_id
  SMTYP: sampler_type_code
  SMVOL: sampled_volume_l
  SPLIT: sample_splitting_code
  STAGE: dev_stage_code
  STATN: reported_station_name
  STIME: sample_time
  TAXNM: taxonomist
  VFLAG: quality_flag
  WADEP: water_depth_m
  WAVES: wave_observation_code
  WEATH: weather_observation_code
  WETWT: used_indwetwt.DIVIDE.1000
  WETWTM2: COPY_VARIABLE_MULTIPLY.Wet weight/area.mg/m2.1000
  WETWTM3: COPY_VARIABLE_MULTIPLY.Wet weight/volume.mg/m3.1000
  WINDIR: wind_direction_code
  WINDR: wind_direction_code
  WINSP: wind_speed_ms
  WIRAN: wire_angle_deg
  WLTYP: water_land_station_type_code
ZP_UMSC-SMHI:
  ABUND/M2: COPY_VARIABLE.Abundance.ind/m2
  ABUNDM2: COPY_VARIABLE.Abundance.ind/m2
  ABUNDM3: COPY_VARIABLE.Abundance.ind/m3
  ACKR_ANA: analytical_laboratory_accreditated
  ACKR_SMP: sampling_laboratory_accreditated
  AIRPRES: air_pressure_hpa
  AIRTEMP: air_temperature_degc
  ALABO: analytical_laboratory_code
  ANADATE: analysis_date
  ANA_RESP: analysed_by
  CCONT: COPY_VARIABLE.Carbon content.ug/analysed sample fraction
  CLMET: calculation_method
  CLOUD: cloud_observation_code
  COMNT_ABU: variable_comment
  COMNT_SAMP: sample_comment
  COMNT_SITE: visit_comment
  COMNT_VAR: variable_comment
  COMNT_VISIT: visit_comment
  COUNT: COPY_VARIABLE.# counted.ind/analysed sample fraction
  COUNTNR: COPY_VARIABLE.# counted.ind/analysed sample fraction
  CPORT: counted_portions
  CRUIS: expedition_id
  CRUISE_NO: expedition_id
  DRYWT: COPY_VARIABLE.Dry weight.mg/analysed sample fraction
  EXPID: expedition_id
  FLOW_READ: flowmeter_length_m
  ICEOB: ice_observation_code
  INDCOUNT: COPY_VARIABLE.# counted.ind/analysed sample fraction
  INDWETWT: used_indwetwt.MULTIPLY.1000
  LATIT: visit_reported_latitude
  LATNM: reported_scientific_name
  LAT_DEG: latitude_deg
  LAT_MIN: latitude_min
  LENGTH_AVERAGE: COPY_VARIABLE.Length (mean).um
  LENGTH_MEAN: COPY_VARIABLE.Length (mean).um
  LENGTH_MEDIAN: COPY_VARIABLE.Length (median).um
  LONGI: visit_reported_longitude
  LONG_DEG: longitude_deg
  LONG_MIN: longitude_min
  Latitude_deg: latitude_deg
  Latitude_min: latitude_min
  Longitude_deg: longitude_deg
  Longitude_min: longitude_min
  MAGNI: magnification
  MESHS: mesh_size_um
  METDC: method_documentation
  METFP: preservation_method_code
  MNDEP: sample_min_depth_m
  MPROG: monitoring_program_code
  MSTAT: monitoring_station_type_code
  MXDEP: sample_max_depth_m
  MYEAR: visit_year
  MYYEAR: visit_year
  NPORT: number_of_portions
  ORDERER: sample_orderer_code
  PDMET: plankton_sampling_method_code
  POSYS: positioning_system_code
  PROJ: sample_project_code
  PROJ_NAME: sample_project_code
  PURPM: monitoring_purpose_code
  QFLAG: quality_flag
  Q_SECCHI: secchi_depth_quality_flag
  REFSK: method_reference_code
  RPSNO: sample_id
  SAREA: sampler_area_cm2
  SDATE: visit_date
  SEAST: wave_observation_code
  SECCHI: secchi_depth_m
  SEQNO: visit_id
  SERNO: visit_id
  SEX: sex_code
  SEXCO: sex_code
  SEXCODE: sex_code
  SFLAG: species_flag_code
  SHIPC: platform_code
  SIZCL: size_class
  SIZCL_MAX: size_max_um
  SIZCL_MIN: size_min_um
  SLABO: sampling_laboratory_code
  SMPNO: sample_id
  SMTYP: sampler_type_code
  SMVOL: sampled_volume_l
  SPLIT: sample_splitting_code
  STAGE: dev_stage_code
  STATN: reported_station_name
  STIME: sample_time
  TAXNM: taxonomist
  WADEP: water_depth_m
  WAVES: wave_observation_code
  WEATH: weather_observation_code
  WETWT: COPY_VARIABLE_MULTIPLY.Wet weight.mg/analysed sample fraction.1000
  WETWTM2: COPY_VARIABLE_MULTIPLY.Wet weight/area.mg/m2.1000
  WETWTM3: COPY_VARIABLE_MULTIPLY.Wet weight/volume.mg/m3.1000
  WINDIR: wind_direction_code
  WINDR: wind_direction_code
  WINSP: wind_speed_ms
  WIRAN: wire_angle_deg
  WLTYP: water_land_station_type_code
