EELGRASS:
  ACKR_ANA: analytical_laboratory_accreditated
  ACKR_SMP: sampling_laboratory_accreditated
  ALABO: analytical_laboratory_code
  COMNT_SAMP: sample_comment
  COMNT_VISIT: visit_comment
  COVERAGE%: COPY_VARIABLE.Cover (%).%
  DISTRMAX_DEP: distributionmax_depth
  Datum: visit_date
  FNFLA: fauna_flora_found
  Filmnummer: transect_video_name
  Kommentar: visit_comment
  LATIT: sample_reported_latitude
  LATNM: reported_scientific_name
  LONGI: sample_reported_longitude
  Latitud: sample_reported_latitude
  Lokal: reported_station_name
  Longitud: sample_reported_longitude
  METDC: method_documentation
  MPROG: monitoring_program_code
  MSTAT: monitoring_station_type_code
  MYEAR: visit_year
  ORDERER: sample_orderer_code
  POSYS: positioning_system_code
  PROJ: sample_project_code
  PROJ_NAME: sample_project_code
  PURPM: monitoring_purpose_code
  "Procent av yta t\xE4ckt av \xE5lgr\xE4s": COPY_VARIABLE.Cover (%).%
  REFSK: method_reference_code
  RHIZOMBIOMASSA (G DW/M2): COPY_VARIABLE.Rhizome biomass.g dry weight/m2
  RLABO: reporting_institute_code
  SAREA: sampler_area_m2
  SDATE: visit_date
  SFLAG: species_flag_code
  SHIPC: platform_code
  SKOTTANTAL (ANTAL/M2): COPY_VARIABLE.Shoot density.ind/m2
  SKOTTBIOMASSA (G DW/M2): COPY_VARIABLE.Shoot biomass.g dry weight/m2
  "SKOTTL\xC4NGD MAX (CM)": COPY_VARIABLE.Max shoot length.cm
  "SKOTTL\xC4NGD MEDEL (CM)": COPY_VARIABLE.Average shoot length.cm
  "SKOTTL\xC4NGD MIN (CM)": COPY_VARIABLE.Min shoot length.cm
  SLABO: sampling_laboratory_code
  SMDEP: sample_depth_m
  SMPDEP: sample_depth_m
  SMPNO: sample_id
  SMPSERNO: sample_series_no
  SMP_LATIT: sample_latitude
  SMP_LONGI: sample_longitude
  SMTYP: sampler_type_code
  SOCKERHALT (%): COPY_VARIABLE.Rhizome juice sugar content. % by volume
  STATN: reported_station_name
  STIME: sample_time
  TAXNM: taxonomist
  TOTCOVERAGE%: CREATE_VARIABLE.Total cover of all species (%).%
  "T\xE4thet i den \xE5lgr\xE4st\xE4ckta ytan": COPY_VARIABLE.Density in covered area.%
  "Unders\xF6kning": sample_project_code
  "Vattenst\xE5ndskorrigerat djup (m)": sample_depth_m
  "Vattenst\xE5ndskorrigerat maxdjup": COPY_VARIABLE.Depth distribution (max depth).m
  WADEP: water_depth_m
  WADEP_COR: COPY_VARIABLE.Depth distribution (max depth).m
  WATLD: water_level_deviation_m
  WAVXP: wave_exposure_fetch
  "Ytspecifik T\xE4ckning": COPY_VARIABLE.Substrate specific cover.%
