barcoding:
  ABSOLUTE_ABUND: COPY_VARIABLE.Absolute Abundance.sequences/l
  ACKR_ANA: analytical_laboratory_accreditated
  ACKR_SMP: sampling_laboratory_accreditated
  AIRPRES: air_pressure_hpa
  AIRTEMP: air_temperature_degc
  ALABO: analytical_laboratory_code
  ANADATE: analysis_date
  ANOCONF: annotation_confidence
  ASV_ID: absolute_sequence_variant_id
  BIOINFODATE: bioinformatic_analysis_date
  BIOINFOPIPELINE: bioinformatic_analysis_pipeline
  CLOUD: cloud_observation_code
  COEFF: coefficient
  COMNT_SAMP: sample_comment
  COMNT_VAR: variable_comment
  COMNT_VISIT: visit_comment
  CREP: number_of_replicates
  CRUISE_NO: expedition_id
  EXTRDATE: extraction_date
  FILTTIME: filtration_time
  FILTVOL: volume_filtered
  GENE: gene
  ICEOB: ice_observation_code
  INTSTD: internal_standard
  LATIT: visit_reported_latitude
  LATNM: reported_scientific_name
  LONGI: visit_reported_longitude
  METDC: method_documentation
  METFP: preservation_method_code
  METOA: analysis_method_code
  MNDEP: sample_min_depth_m
  MSTAT: monitoring_station_type_code
  MXDEP: sample_max_depth_m
  MYEAR: visit_year
  NREP: sample_replicate
  ORDERER: sample_orderer_code
  OTU_ID: operational_taxonomic_unit_id
  PDMET: plankton_sampling_method_code
  POSYS: positioning_system_code
  PRIMER: primer_pair
  PROJ: sample_project_code
  QFLAG: quality_flag
  Q_SECCHI: secchi_depth_quality_flag
  READS: COPY_VARIABLE.Reads.number of reads
  REFSK: method_reference_code
  RELATIVE_ABUND: COPY_VARIABLE.Relative Abundance (%).%
  REP: replication
  RLIST: species_reference_list
  SDATE: visit_date
  SECCHI: secchi_depth_m
  SEQUENCE: sequence
  SEQ_ARCHIVE: sequence_archive_accession
  SEQ_PLATFORM: sequence_platform
  SFLAG: species_flag_code
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMPNO: sample_id
  SMTYP: sampler_type_code
  SMVOL: sampled_volume_l
  STATN: reported_station_name
  STIME: sample_time
  STTEMP: storage_temperature
  TRPHY: trophic_type_code
  WAVES: wave_observation_code
  WEATH: weather_observation_code
  WINDIR: wind_direction_code
  WINSP: wind_speed_ms
