Ringed_seal:
  ' COMNT_SAMP': transect_comment
  ACKR_ANA: analytical_laboratory_accreditated
  ACKR_SMP: sampling_laboratory_accreditated
  AIRPRES: air_pressure_hpa
  AIRTEMP: air_temperature_degc
  ALABO: analytical_laboratory_code
  Area: sea_region
  CLOUD: cloud_observation_code
  COEFF: coefficient
  COMNT_TRANS: transect_comment
  COMNT_VAR: variable_comment
  COUNT: COPY_VARIABLE.# counted.ind
  COUNTNR: COPY_VARIABLE.# counted.ind
  FNFLA: fauna_flora_found
  ICEOB: ice_observation_code
  ICE_OBS: coefficient
  IMAGE_ID: image_id
  LATIT: sample_reported_latitude
  LATNM: reported_scientific_name
  LONGI: sample_reported_longitude
  METDC: method_documentation
  MPROG: monitoring_program_code
  MYEAR: visit_year
  OBS_LAT: sample_reported_latitude
  OBS_LONG: sample_reported_longitude
  ORDERER: sample_orderer_code
  PICT_NUMB: image_id
  POSYS: positioning_system_code
  PROJ: sample_project_code
  PROJ_NAME: sample_project_code
  QFLAG: QFLAG.Abundance
  REGION: sea_region
  SDATE: visit_date
  SFLAG: species_flag_code
  SLABO: sampling_laboratory_code
  SMPTIME: sample_time
  SMTYP: sampler_type_code
  START_TRANS_LAT: visit_transect_start_latitude
  START_TRANS_LONG: visit_transect_start_longitude
  STIME: sample_time
  STOP_TRANS_LAT: visit_transect_end_latitude
  STOP_TRANS_LONG: visit_transect_end_longitude
  TAXNM: taxonomist
  TRANSL: transect_length_m
  TRANSW: transect_width_m
  TRANS_FNFLA: fauna_flora_found
  TRANS_ID: transect_id
  TRANS_LAT_START: visit_transect_start_latitude
  TRANS_LAT_STOP: visit_transect_end_latitude
  TRANS_LONG_START: visit_transect_start_longitude
  TRANS_LONG_STOP: visit_transect_end_longitude
  WAVES: wave_observation_code
  WEATH: weather_observation_code
  WINDIR: wind_direction_code
  WINSP: wind_speed_ms
Rseal:
  ABUNDKM2: COPY_VARIABLE.Abundance.ind/km2
  ACKR_ANA: analytical_laboratory_accreditated
  AIRPRES: air_pressure_hpa
  AIRTEMP: air_temperature_degc
  ALABO: analytical_laboratory_code
  Area: sea_region
  CLOUD: cloud_observation_code
  COMNT_SECTION: section_comment
  COMNT_TRANS: transect_comment
  COMNT_VAR: variable_comment
  COUNT: COPY_VARIABLE.# counted.ind
  COUNTNR: COPY_VARIABLE.# counted.ind
  FNFLA: fauna_flora_found
  ICEOB: ice_observation_code
  IMAGE_ID: image_id
  LATNM: reported_scientific_name
  METDC: method_documentation
  MYEAR: visit_year
  ORDERER: sample_orderer_code
  PICT_NUMB: image_id
  PROJ: sample_project_code
  QFLAG: QFLAG.Abundance
  REGION: sea_region
  SDATE: visit_date
  SECTION: section_id
  SECTIONA: section_area_km2
  SFLAG: species_flag_code
  SLABO: sampling_laboratory_code
  SMTYP: sampler_type_code
  STAGE: dev_stage_code
  START_SECTION_LAT: section_start_latitude
  START_SECTION_LONG: section_start_longitude
  START_TRANS_LAT: visit_transect_start_latitude
  START_TRANS_LONG: visit_transect_start_longitude
  STOP_SECTION_LAT: section_end_latitude
  STOP_SECTION_LONG: section_end_longitude
  STOP_TRANS_LAT: visit_transect_end_latitude
  STOP_TRANS_LONG: visit_transect_end_longitude
  TAXNM: taxonomist
  TRANS: transect_id
  WAVES: wave_observation_code
  WEATH: weather_observation_code
  WINDIR: wind_direction_code
  WINSP: wind_speed_ms
