Chla:
  ACKR_ANA: analytical_laboratory_accreditated
  ACKR_SMP: sampling_laboratory_accreditated
  AIRPRES: air_pressure_hpa
  AIRTEMP: air_temperature_degc
  ALABO: analytical_laboratory_code
  ANADATE: analysis_date
  ANMET: analysis_method_code
  CHLAMGM3: COPY_VARIABLE.Chlorophyll-a.ug/l
  CHLA_CONC: COPY_VARIABLE.Chlorophyll-a.ug/l
  CHLA_MGM3: COPY_VARIABLE.Chlorophyll-a.ug/l
  CLOUD: cloud_observation_code
  COMNT: variable_comment
  COMNT_SAMP: sample_comment
  COMNT_VAR: variable_comment
  COMNT_VISIT: visit_comment
  CONC: COPY_VARIABLE.Chlorophyll-a.ug/l
  CPHL: COPY_VARIABLE.Chlorophyll-a.ug/l
  CRUISE_NO: expedition_id
  DETLI: detection_limit
  EDATE: sample_enddate
  ETIME: sample_endtime
  EXPID: expedition_id
  ICEOB: ice_observation_code
  LATIT: visit_reported_latitude
  LMQNT: quantification_limit
  LONGI: visit_reported_longitude
  METCU: method_calculation_uncertainty
  METDC: method_documentation
  METOA: analysis_method_code
  MNDEP: sample_min_depth_m
  MPROG: monitoring_program_code
  MSTAT: monitoring_station_type_code
  MXDEP: sample_max_depth_m
  MYEAR: visit_year
  ORDERER: sample_orderer_code
  POSYS: positioning_system_code
  PRES: air_pressure_hpa
  PROJ: sample_project_code
  PURPM: monitoring_purpose_code
  QCHLA: QFLAG.Chlorophyll-a
  QFLAG: QFLAG.Chlorophyll-a
  Q_CPHL: QFLAG.Chlorophyll-a
  Q_SECCHI: secchi_depth_quality_flag
  Q_SECCI: secchi_depth_quality_flag
  RANA: analysis_range
  REFSK: method_reference_code
  SAFLG: SFLAG.Chlorophyll-a
  SDATE: visit_date
  SEAST: wave_observation_code
  SECCHI: secchi_depth_m
  SECCI: secchi_depth_m
  SERNO: visit_id
  SFLAG: SFLAG.Chlorophyll-a
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMPDATE: sample_date
  SMPNO: sample_id
  SMPSTIME: sample_time
  SMPTIME: sample_time
  SMTYP: sampler_type_code
  SMVOL: sampled_volume_l
  STATN: reported_station_name
  STIME: sample_time
  UNCERT: estimation_uncertainty
  VFLAG: QFLAG.Chlorophyll-a
  WADEP: water_depth_m
  WAVES: wave_observation_code
  WEATH: weather_observation_code
  WINDIR: wind_direction_code
  WINDR: wind_direction_code
  WINSP: wind_speed_ms
  WLTYP: water_land_station_type_code
