NAT:
  ABUND: COPY_VARIABLE.Abundance.ind/m3
  ACKR_ANA: analytical_laboratory_accreditated
  ACKR_SMP: sampling_laboratory_accreditated
  AIRPRES: air_pressure_hpa
  AIRTEMP: air_temperature_degc
  ALABO: analytical_laboratory_code
  ANADATE: analysis_date
  ANA_RESP: analysed_by
  BMCCONT: COPY_VARIABLE.Carbon content.mg/m3
  CLMET: calculation_method
  CLOUD: cloud_observation_code
  COMNT_ABUN: variable_comment
  COMNT_SAMP: sample_comment
  COMNT_SAMPLE: sample_comment
  COMNT_VAR: variable_comment
  COMNT_VISIT: visit_comment
  COUNT: COPY_VARIABLE.# counted.ind/analysed sample fraction
  COUNTNR: COPY_VARIABLE.# counted.ind/analysed sample fraction
  CPORT: counted_portions
  CRUISE_NO: expedition_id
  DISPLA: COPY_VARIABLE.Displacement volume.ml
  EXPID: expedition_id
  FLOW_READ: flowmeter_length_m
  ICEOB: ice_observation_code
  INDCOUNT: COPY_VARIABLE.# counted.ind/analysed sample fraction
  LATIT: visit_reported_latitude
  LATNM: reported_scientific_name
  LENGTH: COPY_VARIABLE.Length.mm
  LENGTH_MEAN: COPY_VARIABLE.Length mean.mm
  LENGTH_MEDIAN: COPY_VARIABLE.Length median.mm
  LONGI: visit_reported_longitude
  MAGNI: magnification
  MESHS: mesh_size_um
  METDC: method_documentation
  METFP: preservation_method_code
  MNDEP: sample_min_depth_m
  MPROG: monitoring_program_code
  MSTAT: monitoring_station_type_code
  MXDEP: sample_max_depth_m
  MYEAR: visit_year
  NPORT: number_of_portions
  ORDERER: sample_orderer_code
  PDMET: plankton_sampling_method_code
  POSYS: positioning_system_code
  PROJ: sample_project_code
  PROJ_NAME: sample_project_code
  QFLAG: quality_flag
  Q_SECCHI: secchi_depth_quality_flag
  REFSK: method_reference_code
  SAREA: sampler_area_m2
  SDATE: visit_date
  SEAST: wave_observation_code
  SECCHI: secchi_depth_m
  SERNO: visit_id
  SEXCO: sex_code
  SEXCODE: sex_code
  SFLAG: species_flag_code
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMPID: sample_id
  SMPNO: sample_id
  SMTYP: sampler_type_code
  SMVOL: sampled_volume_l
  SPLIT: sample_splitting_code
  STAGE: dev_stage_code
  STATN: reported_station_name
  STIME: sample_time
  TAXNM: taxonomist
  VFLAG: quality_flag
  WADEP: water_depth_m
  WAVES: wave_observation_code
  WEATH: weather_observation_code
  WETWT: COPY_VARIABLE.Wet weight.g
  WETWTM3: COPY_VARIABLE.Wet weight/volume.g/m3
  WINDIR: wind_direction_code
  WINDIR_CODE: wind_direction_code
  WINDR: wind_direction_code
  WINSP: wind_speed_ms
  WIRAN: wire_angle_deg
  WLTYP: water_land_station_type_code
ZP_JELLY:
  ABUND: COPY_VARIABLE.Abundance.ind/m3
  ACKR_ANA: analytical_laboratory_accreditated
  ACKR_SMP: sampling_laboratory_accreditated
  AIRPRES: air_pressure_hpa
  AIRTEMP: air_temperature_degc
  ALABO: analytical_laboratory_code
  ANADATE: analysis_date
  ANA_RESP: analysed_by
  BMCCONT: COPY_VARIABLE.Carbon content.ug/m3
  CLMET: calculation_method
  CLOUD: cloud_observation_code
  COMNT_ABUN: variable_comment
  COMNT_SAMP: sample_comment
  COMNT_SAMPLE: sample_comment
  COMNT_VAR: variable_comment
  COMNT_VISIT: visit_comment
  COUNT: COPY_VARIABLE.# counted.ind/analysed sample fraction
  COUNTNR: COPY_VARIABLE.# counted.ind/analysed sample fraction
  CPORT: counted_portions
  CRUISE_NO: expedition_id
  EXPID: expedition_id
  FLOW_READ: flowmeter_length_m
  ICEOB: ice_observation_code
  INDCOUNT: COPY_VARIABLE.# counted.ind/analysed sample fraction
  LATIT: visit_reported_latitude
  LATNM: reported_scientific_name
  LENGTH: COPY_VARIABLE.Length.mm
  LONGI: visit_reported_longitude
  MAGNI: magnification
  MESHS: mesh_size_um
  METDC: method_documentation
  METFP: preservation_method_code
  MNDEP: sample_min_depth_m
  MPROG: monitoring_program_code
  MSTAT: monitoring_station_type_code
  MXDEP: sample_max_depth_m
  MYEAR: visit_year
  NPORT: number_of_portions
  ORDERER: sample_orderer_code
  PDMET: plankton_sampling_method_code
  POSYS: positioning_system_code
  PROJ: sample_project_code
  PROJ_NAME: sample_project_code
  QFLAG: quality_flag
  Q_SECCHI: secchi_depth_quality_flag
  REFSK: method_reference_code
  SAREA: sampler_area_cm2
  SDATE: visit_date
  SEAST: wave_observation_code
  SECCHI: secchi_depth_m
  SERNO: visit_id
  SEXCO: sex_code
  SEXCODE: sex_code
  SFLAG: species_flag_code
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMPID: sample_id
  SMPNO: sample_id
  SMTYP: sampler_type_code
  SMVOL: sampled_volume_l
  SPLIT: sample_splitting_code
  STAGE: dev_stage_code
  STATN: reported_station_name
  STIME: sample_time
  TAXNM: taxonomist
  VFLAG: quality_flag
  WADEP: water_depth_m
  WAVES: wave_observation_code
  WEATH: weather_observation_code
  WETWTM3: COPY_VARIABLE.Wet weight/volume.g/m3
  WINDIR_CODE: wind_direction_code
  WINDR: wind_direction_code
  WINSP: wind_speed_ms
  WIRAN: wire_angle_deg
  WLTYP: water_land_station_type_code
