SED_SUSE:
  '###METCO': method_incubation
  ACKR_ANA: analytical_laboratory_accreditated
  ACKR_SMP: sampling_laboratory_accreditated
  ALABO: analytical_laboratory_code
  CLOUD: cloud_observation_code
  COMNT: variable_comment
  C_PROC: COPY_VARIABLE.Sedimentation C-fraction.% dw
  DW_GM2D: COPY_VARIABLE.Sedimentation rate (dw).g dw/m2/day
  EDATE: sample_enddate
  EXPID: expedition_id
  FINFL: factors_influencing_code
  ICEOB: ice_observation_code
  IETIM: incubation_end_time
  INAIR: insolation_air
  INTIM: incubation_time_h
  ISTIM: incubation_start_time
  LATIT: visit_reported_latitude
  LONGI: visit_reported_longitude
  MESHS: mesh_size_um
  METDC: method_documentation
  METFP: preservation_method_code
  MPROG: monitoring_program_code
  MSTAT: monitoring_station_type_code
  MYEAR: visit_year
  NOAGG: aggregated_subsamples
  N_PROC: COPY_VARIABLE.Sedimentation N-fraction.% dw
  ORDERER: sample_orderer_code
  POSYS: positioning_system_code
  PROJ: sample_project_code
  P_PROC: COPY_VARIABLE.Sedimentation P-fraction.% dw
  QC: QFLAG.Sedimentation C-fraction
  QDEP: sample_depth_quality_flag
  QDW: QFLAG.Sedimentation rate (dw)
  QN: QFLAG.Sedimentation N-fraction
  QP: QFLAG.Sedimentation P-fraction
  REFSK: method_reference_code
  SDATE: visit_date
  SEAST: wave_observation_code
  SED_C: COPY_VARIABLE.Sedimentation C-fraction.% dw
  SED_C%: COPY_VARIABLE.Sedimentation C-fraction.% dw
  SED_DW: COPY_VARIABLE.Sedimentation rate (dw).g dw/m2/day
  SED_N: COPY_VARIABLE.Sedimentation N-fraction.% dw
  SED_N%: COPY_VARIABLE.Sedimentation N-fraction.% dw
  SED_P: COPY_VARIABLE.Sedimentation P-fraction.% dw
  SED_P%: COPY_VARIABLE.Sedimentation P-fraction.% dw
  SERNO: visit_id
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMDEP: sample_depth_m
  SMPNO: sample_id
  SMTYP: sampler_type_code
  STATN: reported_station_name
  STIME: sample_time
  S_COR_FAC: salinity_correction
  WADEP: water_depth_m
  WEATH: weather_observation_code
  WINDR: wind_direction_code
  WINSP: wind_speed_ms
  WLTYP: water_land_station_type_code
SED_UMSC:
  '###METCO': method_incubation
  ACKR_ANA: analytical_laboratory_accreditated
  ACKR_SMP: sampling_laboratory_accreditated
  ALABO: analytical_laboratory_code
  CLOUD: cloud_observation_code
  COMNT: variable_comment
  COMNT_EXP: visit_comment
  COMNT_SAMP: sample_comment
  C_PROC: COPY_VARIABLE.Sedimentation C-fraction.% dw
  DW_GM2D: COPY_VARIABLE.Sedimentation rate (dw).g dw/m2/day
  EDATE: sample_enddate
  EXPID: expedition_id
  IETIM: incubation_end_time
  INAIR: insolation_air
  INTIM: incubation_time_h
  ISTIM: incubation_start_time
  LATIT: visit_reported_latitude
  LONGI: visit_reported_longitude
  METDC: method_documentation
  METFP: preservation_method_code
  MPROG: monitoring_program_code
  MYEAR: visit_year
  N_PROC: COPY_VARIABLE.Sedimentation N-fraction.% dw
  ORDERER: sample_orderer_code
  PROJ: sample_project_code
  P_PROC: COPY_VARIABLE.Sedimentation P-fraction.% dw
  QDEP: sample_depth_quality_flag
  Q_SED_AL: QFLAG.Sedimentation Al-fraction
  Q_SED_C: QFLAG.Sedimentation C-fraction
  Q_SED_FE: QFLAG.Sedimentation Fe-fraction
  Q_SED_MG: QFLAG.Sedimentation Mg-fraction
  Q_SED_MN: QFLAG.Sedimentation Mn-fraction
  Q_SED_N: QFLAG.Sedimentation N-fraction
  Q_SED_P: QFLAG.Sedimentation P-fraction
  Q_SED_RATE_DW: QFLAG.Sedimentation rate (dw)
  Q_SED_SI: QFLAG.Sedimentation Si-fraction
  REFSK: method_reference_code
  SDATE: visit_date
  SED_AL: COPY_VARIABLE.Sedimentation Al-fraction.% dw
  SED_C: COPY_VARIABLE.Sedimentation C-fraction.% dw
  SED_FE: COPY_VARIABLE.Sedimentation Fe-fraction.% dw
  SED_MG: COPY_VARIABLE.Sedimentation Mg-fraction.% dw
  SED_MN: COPY_VARIABLE.Sedimentation Mn-fraction.ppm dw
  SED_N: COPY_VARIABLE.Sedimentation N-fraction.% dw
  SED_P: COPY_VARIABLE.Sedimentation P-fraction.% dw
  SED_RATE_DW: COPY_VARIABLE.Sedimentation rate (dw).g dw/m2/day
  SED_SI: COPY_VARIABLE.Sedimentation Si-fraction.% dw
  SERNO: visit_id
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMDEP: sample_depth_m
  SMPDEP: sample_depth_m
  SMPNO: sample_id
  STATN: reported_station_name
  WADEP: water_depth_m
