Primprod_BIOMAD_SUSE_UMSC:
  ACKR_ANA: analytical_laboratory_accreditated
  ACKR_SMP: sampling_laboratory_accreditated
  ALABO: analytical_laboratory_code
  CLOUD: cloud_observation_code
  COMNT_PROD: variable_comment
  COMNT_SAMP: sample_comment
  COMNT_SITE: visit_comment
  CPROD_GM3D: COPY_VARIABLE_MULTIPLY.Carbon production/day.mgC/m3/d.1000
  CPROD_GM3H: COPY_VARIABLE_MULTIPLY.Carbon production/hour.mgC/m3/h.1000
  EXPID: expedition_id
  ICEOB: ice_observation_code
  IETIM: incubation_end_time
  INAIR: insolation_air
  INTIM: incubation_time_h
  ISTIM: incubation_start_time
  LATIT: visit_reported_latitude
  LONGI: visit_reported_longitude
  METCO: analysis_method_code
  METDC: method_documentation
  MPROG: monitoring_program_code
  MSTAT: monitoring_station_type_code
  MYEAR: visit_year
  ORDERER: sample_orderer_code
  PARAD_UEM2: COPY_VARIABLE.PAR at sampling depth.uE/m2/s
  PARAD_UEM2S: COPY_VARIABLE.PAR at sampling depth.uE/m2/s
  PARFLG: QFLAG.PAR at sampling depth
  POSYS: positioning_system_code
  PRDFLG: QFLAG.Carbon production.mgC/m3/d
  PRHFLG: QFLAG.Carbon production.mgC/m3/h
  PROJ: sample_project_code
  REFDC: method_documentation
  REFSK: method_reference_code
  SDATE: visit_date
  SDEPT: sample_depth_m
  SEAST: wave_observation_code
  SERNO: sample_series
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMTYP: sampler_type_code
  STATN: reported_station_name
  STIME: sample_time
  SUBNO: sample_part_id
  WADEP: water_depth_m
  WEATH: weather_observation_code
  WINDR: wind_direction_code
  WINSP: wind_speed_ms
  WLTYP: water_land_station_type_code
  _uEm2s: incubation_radiation_e
Primprod_INCUB:
  ACKR_ANA: analytical_laboratory_accreditated
  ACKR_SMP: sampling_laboratory_accreditated
  ALABO: analytical_laboratory_code
  ALKALINITET: CREATE_VARIABLE.Alkalinity.mmol/l
  ALKY: CREATE_VARIABLE.Alkalinity.mmol/l
  ATT_COEFF: attenuation_coeff
  Alkalinitet: CREATE_VARIABLE.Alkalinity.mmol/l
  Antal v?den i P/E-kurvan: n_step_PI
  "Antal v\xE4rden i P/E-kurvan": n_step_PI
  CHLA_mg/m3: CREATE_VARIABLE.Chlorophyll-a.ug/l
  CLOUD: cloud_observation_code
  CO2TOT: CREATE_VARIABLE.Total CO2.mmol/l
  COMNT_CALC: calculation_comment
  COMNT_MET: method_comment
  COMNT_SAMP: sample_comment
  COMNT_VAR: variable_comment
  COMNT_VISIT: visit_comment
  COMT_VAR: variable_comment
  CPROD_GM3D: COPY_VARIABLE_MULTIPLY.Carbon production/day.mgC/m3/d.1000
  CRUISE_NO: expedition_id
  DARKM3H: CREATE_VARIABLE.Carbon production in darkness.mgC/m3/h
  DARK_PROD: CREATE_VARIABLE.Carbon production in darkness.mgC/m3/h
  DEPTH: sample_depth_m
  DEPTH CALCULATED PRODUCTION: sample_depth_m
  DPMA: DPM_added
  DPMD: DPM_darkness
  DPMS: DPM_sample
  EXPID: expedition_id
  EXT_COEFF: attenuation_coeff
  FFACTOR: ffactor_gargas1975
  FFACTOR_GARGAS1975: ffactor_gargas1975
  FFAKTOR_GARGAS1975: ffactor_gargas1975
  ICEOB: ice_observation_code
  INCUR: incubation_radiation_e
  INCUR1: incubation_radiation_e
  INCUR2: incubation_radiation_w
  INTIM: incubation_time_h
  LATIT: visit_reported_latitude
  LONGI: visit_reported_longitude
  "Light_day (\xB5E m^-2 d^-1)": insolation_air
  "Light_hour (\xB5E m^-2 s^-1)": incubation_radiation_e
  MEAN_LIGHT_D: insolation_air
  METDC: method_documentation
  METOA: analysis_method_code
  MNDEP: sample_min_depth_m
  MPROG: monitoring_program_code
  MSTAT: monitoring_station_type_code
  MXDEP: sample_max_depth_m
  MYEAR: visit_year
  Metodkommentar: method_comment
  ORDERER: sample_orderer_code
  PH: CREATE_VARIABLE.pH
  PI_SLOPE: CREATE_VARIABLE.Alpha.mgC/m3/h/(uE/m2/s)
  "PI_SLOPE (\xB5mol C dm-3 h-1 (\xB5mol quanta)-1 m2 s)": CREATE_VARIABLE.Alpha.mgC/m3/h/(uE/m2/s)
  PMAX (mg C m^-3 h^-1): CREATE_VARIABLE.Pmax.mgC/m3/h
  POSYS: positioning_system_code
  PROD: COPY_VARIABLE.Carbon prod in light.mgC/m3/h
  PROD  (mg C m^-3 hour^-1): COPY_VARIABLE.Carbon prod in light.mgC/m3/h
  PROD (mg C m^-3 h^-1): COPY_VARIABLE.Carbon prod in light.mgC/m3/h
  PRODDAY: CREATE_VARIABLE.Carbon production.mgC/m3/d
  PRODDAY (mg C m^-3 day^-1): CREATE_VARIABLE.Carbon production.mgC/m3/d
  PRODD_mgC/m3/h: CREATE_VARIABLE.Carbon production in darkness.mgC/m3/h
  PRODM3D: CREATE_VARIABLE.Carbon production.mgC/m3/d
  PRODNETTO_mgC/m3/h: COPY_VARIABLE.Net carbon prod_prod-resp.mgC/m3/h
  PROD_mgC/m3/h: COPY_VARIABLE.Carbon prod in light.mgC/m3/h
  PROJ: sample_project_code
  PSAL: CREATE_VARIABLE.Salinity.o/oo psu
  PURPM: monitoring_purpose_code
  Pmax: CREATE_VARIABLE.Pmax.mgC/m3/h
  Provkomment: sample_comment
  Provkommentar: calculation_comment
  QFLAG: QFLAG.Carbon production.mgC/m2/d
  QFLAG_TOTALPROD_mgC/m2/d: QFLAG.Carbon production.mgC/m2/d
  Q_ATT_COEFF: qflag_attenuation_coeff
  Q_EXT_COEFF: qflag_attenuation_coeff
  Q_PRIMPROD: QFLAG.Carbon production.mgC/m3/h
  Q_SECCHI: QFLAG.Secchi depth
  R2: R2_PI_curve
  R2P1: R2_PI_curve
  REFSK: method_reference_code
  SALT_BTL: COPY_VARIABLE.Salinity bottle.o/oo psu
  SDATE: visit_date
  SDEPT: sample_depth_m
  SECCHI: secchi_depth_m
  SERNO: sample_series
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMPNO: sample_id
  SMTYP: sampler_type_code
  STATN: reported_station_name
  STIME: sample_time
  SUBNO: sample_part_id
  Salthalt: CREATE_VARIABLE.Salinity.o/oo psu
  TEMP: CREATE_VARIABLE.Temperature.C
  TEMP_BTL: CREATE_VARIABLE.Temperature bottle.C
  TOTALPROD: CREATE_VARIABLE.Carbon production.mgC/m2/d
  TOTALPROD_mgC/m2/d: CREATE_VARIABLE.Carbon production.mgC/m2/d
  TOTCO2: CREATE_VARIABLE.Total CO2.mmol/l
  Temp: CREATE_VARIABLE.Temperature.C
  Tot12CO2: CREATE_VARIABLE.Total CO2.mmol/l
  WADEP: water_depth_m
  WAVES: wave_observation_code
  WEATH: weather_observation_code
  WINDIR: wind_direction_code
  WINDR: wind_direction_code
  WINSP: wind_speed_ms
  WLTYP: water_land_station_type_code
  nPI_SLOPE: n_step_PI_slope
  pH: CREATE_VARIABLE.pH
Primprod_INSITU:
  ACKR_SMP: sampling_laboratory_accreditated
  ALABO: analytical_laboratory_code
  BATCH: C14_batch
  "BER\xC4KNAD_ALKALINITET": CREATE_VARIABLE.Alkalinity.mmol/l
  "BER\xC4KNAD_LFAC": COPY_VARIABLE.Daylight conversion factor
  "BER\xC4KNAD_TOTCO2": CREATE_VARIABLE.Total CO2.mmol/l
  "BER\xC4KNAT_PH_0M": CREATE_VARIABLE.pH at 0 m
  "BER\xC4KNAT_PH_20M": CREATE_VARIABLE.pH at 20 m
  CHLA_MEAN_0-10m_mg/m3: COPY_VARIABLE.Mean Chl a concentration 0-10m.mg Chl a/m3
  CHLA_mg/m3: COPY_VARIABLE.Chlorophyll-a.ug/l
  CLOUD: cloud_observation_code
  COMNT_SAMP: sample_comment
  COMNT_VAR: variable_comment
  DPMA: DPM_added
  DPMS: DPM_sample
  ICEOB: ice_observation_code
  INCUR: incubation_radiation_e
  INTEGPROD_mgC/m2/h: CREATE_VARIABLE.Integrated carbon production.mgC/m2/h
  INTIM: incubation_time_h
  ISTIM: incubation_start_time
  LATIT: visit_reported_latitude
  LONGI: visit_reported_longitude
  METDC: method_documentation
  METOA: analysis_method_code
  MNDEP: sample_min_depth_m
  MPROG: monitoring_program_code
  MSTAT: monitoring_station_type_code
  MXDEP: sample_max_depth_m
  MYEAR: visit_year
  ORDERER: sample_orderer_code
  PARAD_UEM2S: COPY_VARIABLE.PAR at sampling depth.uE/m2/s
  POSYS: positioning_system_code
  PROD/CHLA: COPY_VARIABLE.Chl a-specific production.mgC/mgChl a/h
  PRODD_mgC/m3/h: COPY_VARIABLE.Carbon production in darkness.mgC/m3/h
  PRODL_mgC/m3/h: COPY_VARIABLE.Carbon prod in light.mgC/m3/h
  PRODNETTO_mgC/m3/h: COPY_VARIABLE.Net carbon prod_prod-resp.mgC/m3/h
  PROJ: sample_project_code
  PSAL: COPY_VARIABLE.Salinity.o/oo psu
  QFLAG_PRODNETTO_mgC/m3/h: QFLAG.Net carbon prod_prod-resp
  REFSK: method_reference_code
  RLABO: reporting_institute_code
  SDATE: visit_date
  SEAST: wave_observation_code
  SECCHI: secchi_depth_m
  SERNO: sample_series
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMPDEP: sample_depth_m
  SMPNO: sample_id
  SMTYP: sampler_type_code
  STATN: reported_station_name
  STIME: sample_time
  SUBNO: sample_part_id
  TEMP: CREATE_VARIABLE.Temperature.C
  TOTALPROD_mgC/m2/d: CREATE_VARIABLE.Carbon production.mgC/m2/d
  WADEP: water_depth_m
  WEATH: weather_observation_code
  WEATH_COMNT: visit_comment
  WINDR: wind_direction_code
  WINDR_DEGREE: wind_direction_code
  WINSP: wind_speed_ms
  WLTYP: water_land_station_type_code
Primprod_KMRS:
  ACKR_SMP: sampling_laboratory_accreditated
  ALABO: analytical_laboratory_code
  BATCH: C14_batch
  "BER\xC4KNAD_ALKALINITET": CREATE_VARIABLE.Alkalinity.mmol/l
  "BER\xC4KNAD_LFAC": COPY_VARIABLE.Daylight conversion factor
  "BER\xC4KNAD_TOTCO2": CREATE_VARIABLE.Total CO2.mmol/l
  "BER\xC4KNAT_PH_0M": CREATE_VARIABLE.pH at 0 m
  "BER\xC4KNAT_PH_20M": CREATE_VARIABLE.pH at 20 m
  CHLA_MEAN_0-10m_mg/m3: COPY_VARIABLE.Mean Chl a concentration 0-10m.mg Chl a/m3
  CHLA_mg/m3: COPY_VARIABLE.Chlorophyll-a.ug/l
  CLOUD: cloud_observation_code
  COMNT_SAMP: sample_comment
  COMNT_VAR: variable_comment
  DPMA: DPM_added
  DPMS: DPM_sample
  ICEOB: ice_observation_code
  INCUR: incubation_radiation_e
  INTEGPROD_mgC/m2/h: CREATE_VARIABLE.Integrated carbon production.mgC/m2/h
  INTIM: incubation_time_h
  ISTIM: incubation_start_time
  LATIT: visit_reported_latitude
  LONGI: visit_reported_longitude
  METDC: method_documentation
  METOA: analysis_method_code
  MNDEP: sample_min_depth_m
  MPROG: monitoring_program_code
  MSTAT: monitoring_station_type_code
  MXDEP: sample_max_depth_m
  MYEAR: visit_year
  ORDERER: sample_orderer_code
  PARAD_UEM2S: COPY_VARIABLE.PAR at sampling depth.uE/m2/s
  POSYS: positioning_system_code
  PROD/CHLA: COPY_VARIABLE.Chl a-specific production.mgC/mgChl a/h
  PRODD_mgC/m3/h: CREATE_VARIABLE.Carbon production in darkness.mgC/m3/h
  PRODL_mgC/m3/h: COPY_VARIABLE.Carbon prod in light.mgC/m3/h
  PRODNETTO_mgC/m3/h: COPY_VARIABLE.Net carbon prod_prod-resp.mgC/m3/h
  PROJ: sample_project_code
  PSAL: COPY_VARIABLE.Salinity.o/oo psu
  QFLAG_PRODNETTO_mgC/m3/h: QFLAG.Net carbon prod_prod-resp
  REFSK: method_reference_code
  RLABO: reporting_institute_code
  SDATE: visit_date
  SEAST: wave_observation_code
  SECCHI: secchi_depth_m
  SERNO: sample_series
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMPDEP: sample_depth_m
  SMPNO: sample_id
  SMTYP: sampler_type_code
  STATN: reported_station_name
  STIME: sample_time
  SUBNO: sample_part_id
  TEMP: CREATE_VARIABLE.Temperature.C
  TOTALPROD_mgC/m2/d: CREATE_VARIABLE.Carbon production.mgC/m2/d
  WADEP: water_depth_m
  WEATH: weather_observation_code
  WEATH_COMNT: visit_comment
  WINDR: wind_direction_code
  WINDR_DEGREE: wind_direction_code
  WINSP: wind_speed_ms
  WLTYP: water_land_station_type_code
Primprod_SMHI:
  ACKR_SMP: sampling_laboratory_accreditated
  ALABO: analytical_laboratory_code
  ALKALINITET: CREATE_VARIABLE.Alkalinity.mmol/l
  ALKY: CREATE_VARIABLE.Alkalinity.mmol/l
  Alkalinitet: CREATE_VARIABLE.Alkalinity.mmol/l
  Antal v?den i P/E-kurvan: n_step_PI
  "Antal v\xE4rden i P/E-kurvan": n_step_PI
  CHLA_mg/m3: CREATE_VARIABLE.Chlorophyll-a.ug/l
  CLOUD: cloud_observation_code
  CO2TOT: CREATE_VARIABLE.Total CO2.mmol/l
  COMNT_SAMP: sample_comment
  COMNT_VAR: variable_comment
  COMT_VAR: variable_comment
  CPROD_GM3D: COPY_VARIABLE_MULTIPLY.Carbon production/day.mgC/m3/d.1000
  DARKM3H: CREATE_VARIABLE.Carbon production in darkness.mgC/m3/h
  DMP (tillsatt): DPM_added
  DMP i prov: DPM_sample
  DPMA: DPM_added
  DPMS: DPM_sample
  INCUR: incubation_radiation_e
  INTIM: incubation_time_h
  "Klorofyllv\xE4rde-slangprov": CREATE_VARIABLE.Chlorophyll-a.ug/l
  LATIT: visit_reported_latitude
  LONGI: visit_reported_longitude
  METCO: analysis_method_code
  METDC: method_documentation
  MNDEP: sample_min_depth_m
  MPROG: monitoring_program_code
  MSTAT: monitoring_station_type_code
  MXDEP: sample_max_depth_m
  MYEAR: visit_year
  ORDERER: sample_orderer_code
  PARAD_UEM2S: COPY_VARIABLE.PAR at sampling depth.uE/m2/s
  PH: CREATE_VARIABLE.pH
  PI_SLOPE: CREATE_VARIABLE.Alpha.mgC/m3/h/(uE/m2/s)
  POSYS: positioning_system_code
  PRODM2D: CREATE_VARIABLE.Carbon production.mgC/m2/d
  PRODM3D: CREATE_VARIABLE.Carbon production.mgC/m3/d
  PRODM3H: COPY_VARIABLE.Net carbon prod_prod-resp.mgC/m3/h
  PROJ: sample_project_code
  PSAL: CREATE_VARIABLE.Salinity.o/oo psu
  Pmax: CREATE_VARIABLE.Pmax.mgC/m3/h
  QFLAG_TOTALPROD_mgC/m2/d: QFLAG.Carbon production.mgC/m2/d
  R2: R2_PI_curve
  R2P1: R2_PI_curve
  REFSK: method_reference_code
  SDATE: visit_date
  SECCHI: secchi_depth_m
  SERNO: sample_series
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMPNO: sample_id
  SMTYP: sampler_type_code
  STATN: reported_station_name
  STIME: sample_time
  SUBNO: sample_part_id
  Salthalt: CREATE_VARIABLE.Salinity.o/oo psu
  TEMP: CREATE_VARIABLE.Temperature.C
  TOTCO2: CREATE_VARIABLE.Total CO2.mmol/l
  Temp: CREATE_VARIABLE.Temperature.C
  Tot12CO2: CREATE_VARIABLE.Total CO2.mmol/l
  WADEP: water_depth_m
  WLTYP: water_land_station_type_code
  k2 = inkubationstid: incubation_time_h
  pH: CREATE_VARIABLE.pH
Primprod_SUSE:
  ACKR_ANA: analytical_laboratory_accreditated
  ACKR_SMP: sampling_laboratory_accreditated
  ALABO: analytical_laboratory_code
  ALKY: CREATE_VARIABLE.Alkalinity.mmol/l
  CLOUD: cloud_observation_code
  CO2TOT: CREATE_VARIABLE.Total CO2.mmol/l
  COMNT_PROD: variable_comment
  COMNT_SAMP: sample_comment
  COMNT_SITE: visit_comment
  COMNT_VAR: variable_comment
  CPROD_GM3D: COPY_VARIABLE_MULTIPLY.Carbon production/day.mgC/m3/d.1000
  CPROD_GM3H: COPY_VARIABLE_MULTIPLY.Carbon production/hour.mgC/m3/h.1000
  CRUISE_NO: expedition_id
  DARK_PROD: CREATE_VARIABLE.Carbon production in darkness.mgC/m3/h
  DPMA: DPM_added
  DPMS: DPM_sample
  ICEOB: ice_observation_code
  IETIM: incubation_end_time
  INAIR: insolation_air
  INTIM: incubation_time_h
  ISTIM: incubation_start_time
  LATIT: visit_reported_latitude
  LONGI: visit_reported_longitude
  METCO: analysis_method_code
  METDC: method_documentation
  MNDEP: sample_min_depth_m
  MPROG: monitoring_program_code
  MSTAT: monitoring_station_type_code
  MXDEP: sample_max_depth_m
  MYEAR: visit_year
  ORDERER: sample_orderer_code
  PARAD_UEM2: QFLAG.PAR at sampling depth
  PARAD_UEM2S: COPY_VARIABLE.PAR at sampling depth.uE/m2/s
  PH: CREATE_VARIABLE.pH
  POSYS: positioning_system_code
  PRDFLG: QFLAG.Carbon production.mgC/m3/d
  PRHFLG: QFLAG.Carbon production.mgC/m3/h
  PROD: CREATE_VARIABLE.Carbon production.mgC/m2/h
  PROJ: sample_project_code
  PURPM: monitoring_purpose_code
  QFLAG: QFLAG.Carbon production.mgC/m2/d
  REFSK: method_reference_code
  SALT_CTD: COPY_VARIABLE.Salinity CTD.o/oo psu
  SDATE: visit_date
  SDEPT: sample_depth_m
  SEAST: wave_observation_code
  SECCHI: secchi_depth_m
  SERNO: sample_series
  SHIPC: platform_code
  SLABO: sampling_laboratory_code
  SMPNO: sample_id
  SMTYP: sampler_type_code
  STATN: reported_station_name
  STIME: sample_time
  SUBNO: sample_part_id
  TEMP_CTD: COPY_VARIABLE.Temperature CTD.C
  TOTCO2: CREATE_VARIABLE.Total CO2.mmol/l
  WADEP: water_depth_m
  WAVES: wave_observation_code
  WEATH: weather_observation_code
  WINDIR: wind_direction_code
  WINDR: wind_direction_code
  WINSP: wind_speed_ms
  WLTYP: water_land_station_type_code
